// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/dart_types.dart';
import 'api/galileo_map.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GalileoMapSessionPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TextureHandlePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  GalileoMapSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    dynamic raw,
  );

  @protected
  TextureHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    dynamic raw,
  );

  @protected
  GalileoMapSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    dynamic raw,
  );

  @protected
  TextureHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    dynamic raw,
  );

  @protected
  GalileoMapSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    dynamic raw,
  );

  @protected
  TextureHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  LayerConfig dco_decode_box_autoadd_layer_config(dynamic raw);

  @protected
  MapSize dco_decode_box_autoadd_map_size(dynamic raw);

  @protected
  MapViewport dco_decode_box_autoadd_map_viewport(dynamic raw);

  @protected
  PanEvent dco_decode_box_autoadd_pan_event(dynamic raw);

  @protected
  RenderConfig dco_decode_box_autoadd_render_config(dynamic raw);

  @protected
  ScaleEvent dco_decode_box_autoadd_scale_event(dynamic raw);

  @protected
  ScrollEvent dco_decode_box_autoadd_scroll_event(dynamic raw);

  @protected
  TouchEvent dco_decode_box_autoadd_touch_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LayerConfig dco_decode_layer_config(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MapPosition dco_decode_map_position(dynamic raw);

  @protected
  MapSize dco_decode_map_size(dynamic raw);

  @protected
  MapViewport dco_decode_map_viewport(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PanEvent dco_decode_pan_event(dynamic raw);

  @protected
  PanEventType dco_decode_pan_event_type(dynamic raw);

  @protected
  (double, double, double, double) dco_decode_record_f_32_f_32_f_32_f_32(
    dynamic raw,
  );

  @protected
  RenderConfig dco_decode_render_config(dynamic raw);

  @protected
  ScaleEvent dco_decode_scale_event(dynamic raw);

  @protected
  ScaleEventType dco_decode_scale_event_type(dynamic raw);

  @protected
  ScrollEvent dco_decode_scroll_event(dynamic raw);

  @protected
  TouchEvent dco_decode_touch_event(dynamic raw);

  @protected
  TouchEventType dco_decode_touch_event_type(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  GalileoMapSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    SseDeserializer deserializer,
  );

  @protected
  TextureHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    SseDeserializer deserializer,
  );

  @protected
  GalileoMapSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    SseDeserializer deserializer,
  );

  @protected
  TextureHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    SseDeserializer deserializer,
  );

  @protected
  GalileoMapSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    SseDeserializer deserializer,
  );

  @protected
  TextureHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  LayerConfig sse_decode_box_autoadd_layer_config(SseDeserializer deserializer);

  @protected
  MapSize sse_decode_box_autoadd_map_size(SseDeserializer deserializer);

  @protected
  MapViewport sse_decode_box_autoadd_map_viewport(SseDeserializer deserializer);

  @protected
  PanEvent sse_decode_box_autoadd_pan_event(SseDeserializer deserializer);

  @protected
  RenderConfig sse_decode_box_autoadd_render_config(
    SseDeserializer deserializer,
  );

  @protected
  ScaleEvent sse_decode_box_autoadd_scale_event(SseDeserializer deserializer);

  @protected
  ScrollEvent sse_decode_box_autoadd_scroll_event(SseDeserializer deserializer);

  @protected
  TouchEvent sse_decode_box_autoadd_touch_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LayerConfig sse_decode_layer_config(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MapPosition sse_decode_map_position(SseDeserializer deserializer);

  @protected
  MapSize sse_decode_map_size(SseDeserializer deserializer);

  @protected
  MapViewport sse_decode_map_viewport(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PanEvent sse_decode_pan_event(SseDeserializer deserializer);

  @protected
  PanEventType sse_decode_pan_event_type(SseDeserializer deserializer);

  @protected
  (double, double, double, double) sse_decode_record_f_32_f_32_f_32_f_32(
    SseDeserializer deserializer,
  );

  @protected
  RenderConfig sse_decode_render_config(SseDeserializer deserializer);

  @protected
  ScaleEvent sse_decode_scale_event(SseDeserializer deserializer);

  @protected
  ScaleEventType sse_decode_scale_event_type(SseDeserializer deserializer);

  @protected
  ScrollEvent sse_decode_scroll_event(SseDeserializer deserializer);

  @protected
  TouchEvent sse_decode_touch_event(SseDeserializer deserializer);

  @protected
  TouchEventType sse_decode_touch_event_type(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    GalileoMapSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    TextureHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    GalileoMapSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    TextureHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    GalileoMapSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    TextureHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_layer_config(
    LayerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_map_size(MapSize self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_map_viewport(
    MapViewport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pan_event(
    PanEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_render_config(
    RenderConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scale_event(
    ScaleEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scroll_event(
    ScrollEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_touch_event(
    TouchEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_layer_config(LayerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_map_position(MapPosition self, SseSerializer serializer);

  @protected
  void sse_encode_map_size(MapSize self, SseSerializer serializer);

  @protected
  void sse_encode_map_viewport(MapViewport self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_pan_event(PanEvent self, SseSerializer serializer);

  @protected
  void sse_encode_pan_event_type(PanEventType self, SseSerializer serializer);

  @protected
  void sse_encode_record_f_32_f_32_f_32_f_32(
    (double, double, double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_render_config(RenderConfig self, SseSerializer serializer);

  @protected
  void sse_encode_scale_event(ScaleEvent self, SseSerializer serializer);

  @protected
  void sse_encode_scale_event_type(
    ScaleEventType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scroll_event(ScrollEvent self, SseSerializer serializer);

  @protected
  void sse_encode_touch_event(TouchEvent self, SseSerializer serializer);

  @protected
  void sse_encode_touch_event_type(
    TouchEventType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGalileoMapSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTextureHandle(
    int ptr,
  );
}
