// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dart_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `request_map_redraw`

/// Initialize the Galileo Flutter plugin with FFI pointer for irondash
Future<void> galileoFlutterInit({required PlatformInt64 ffiPtr}) =>
    RustLib.instance.api.crateApiApiGalileoFlutterInit(ffiPtr: ffiPtr);

/// Marks the session as alive (called periodically from Flutter)
Future<void> markSessionAlive({required int sessionId}) =>
    RustLib.instance.api.crateApiApiMarkSessionAlive(sessionId: sessionId);

/// Destroys all streams for a given engine
Future<void> destroyAllEngineSessions({required PlatformInt64 engineId}) =>
    RustLib.instance.api.crateApiApiDestroyAllEngineSessions(
      engineId: engineId,
    );

/// Destroys a specific session
Future<void> destroySession({required int sessionId}) =>
    RustLib.instance.api.crateApiApiDestroySession(sessionId: sessionId);

/// Adds a layer to a session
Future<void> addSessionLayer({
  required int sessionId,
  required LayerConfig layerConfig,
}) => RustLib.instance.api.crateApiApiAddSessionLayer(
  sessionId: sessionId,
  layerConfig: layerConfig,
);
