// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dart_types.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MapPosition`, `MapViewport`, `MouseButtonState`, `MouseButton`, `MouseButtonsState`, `MouseEvent`, `Point2`, `UserEvent`, `_Vector2f64`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Size < u32 >>>
abstract class SizeU32 implements RustOpaqueInterface {}

@freezed
sealed class LayerConfig with _$LayerConfig {
  const LayerConfig._();

  /// OpenStreetMap raster tile layer
  const factory LayerConfig.osm() = LayerConfig_Osm;

  /// Custom raster tile layer with URL template
  const factory LayerConfig.rasterTiles({
    required String urlTemplate,
    String? attribution,
  }) = LayerConfig_RasterTiles;
}

class MapInitConfig {
  final (double, double) latlon;
  final int zoomLevel;
  final MapSize mapSize;

  /// Frames per second for the render loop (default: 30)
  final int fps;

  /// Enable multisampling anti-aliasing
  final bool enableMultisampling;

  /// Background color as RGBA (0.0-1.0 range)
  final (double, double, double, double) backgroundColor;

  const MapInitConfig({
    required this.latlon,
    required this.zoomLevel,
    required this.mapSize,
    required this.fps,
    required this.enableMultisampling,
    required this.backgroundColor,
  });

  static Future<MapInitConfig> default_() =>
      RustLib.instance.api.crateApiDartTypesMapInitConfigDefault();

  @override
  int get hashCode =>
      latlon.hashCode ^
      zoomLevel.hashCode ^
      mapSize.hashCode ^
      fps.hashCode ^
      enableMultisampling.hashCode ^
      backgroundColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapInitConfig &&
          runtimeType == other.runtimeType &&
          latlon == other.latlon &&
          zoomLevel == other.zoomLevel &&
          mapSize == other.mapSize &&
          fps == other.fps &&
          enableMultisampling == other.enableMultisampling &&
          backgroundColor == other.backgroundColor;
}

/// Physical size of the map in pixels.
class MapSize {
  final int width;
  final int height;

  const MapSize({required this.width, required this.height});

  Future<SizeU32> asGalileo() =>
      RustLib.instance.api.crateApiDartTypesMapSizeAsGalileo(that: this);

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapSize &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}
